name: ACUS315
channels:
- conda-forge
- anaconda
dependencies:
- python=3.8
- portaudio
- pip
- numpy
- nodejs
- scipy
- matplotlib
- jupyter
- pip:
  - pytta
  - ipympl
  - jupyter_contrib_nbextensions
